"""Add user role

Revision ID: 003
Revises: 002
Create Date: 2026-05-09 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, add the role column with default value
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'SELLER', 'CUSTOMER', name='userrole'), nullable=True))
    
    # Update existing users to have CUSTOMER role
    op.execute("UPDATE users SET role = 'CUSTOMER' WHERE role IS NULL")
    
    # Make the column non-nullable
    op.alter_column('users', 'role', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
